name: documentation
on:
  push:
    # Comment out these two lines if you'd like to test that the mkdocs-material GitHub
    # action successfully runs and publishes to GitHub pages
    branches:
      - main
permissions:
  contents: write
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@main
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements/requirements-mkdocs.txt

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@main
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: mkdocs gh-deploy --force